# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: warpcore
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile
    - GH_REPO_REF: github.com/NTAP/warpcore.git

# Install dependencies
addons:
  apt:
    packages:
      - cmake
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - cmake .

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - sh ./push-to-gh-pages.sh
